# Generated by Django 3.2 on 2021-12-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sold',
            field=models.BooleanField(default=True),
        ),
    ]
