# Generated by Django 3.2 on 2022-01-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
