# Generated by Django 3.2 on 2021-12-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0002_category_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
