# Generated by Django 3.2 on 2022-01-11 17:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0003_auto_20220107_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='list_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
