# Generated by Django 3.2 on 2021-12-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0003_category_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available',
        ),
    ]
