# Generated by Django 3.2 on 2021-12-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0004_remove_category_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%y/%m/%d'),
        ),
    ]
