# Generated by Django 3.2 on 2022-01-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0005_auto_20220111_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='image8',
        ),
    ]
