# Generated by Django 3.2 on 2021-12-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(default='Yorum giriniz.', max_length=500)),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
