# Generated by Django 3.2 on 2021-12-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image5',
        ),
    ]
