# Generated by Django 3.2 on 2021-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0008_auto_20211212_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bathroom',
            field=models.CharField(db_index=True, default=21, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='contunie',
            field=models.CharField(db_index=True, default=21, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='finish',
            field=models.CharField(db_index=True, default=21, max_length=20),
            preserve_default=False,
        ),
    ]
