# Generated by Django 3.2 on 2021-12-20 16:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimar', '0009_auto_20211212_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
